name = "SetPropagation_FEM_Examples"
uuid = "4abb1162-9935-42bc-9788-8314dfa4607d"
authors = ["mforets <mforets@gmail.com>", "dfcaporale <dfcaporale@gmail.com>", "jorgepz <jorgepz@fing.edu.uy>"]
version = "0.1.0"

[deps]
MAT = "23992714-dd62-5051-b70f-ba57cb901cac"
ReachabilityAnalysis = "1e97bd63-91d1-579d-8e8d-501d2b57c93f"

[compat]
MAT = "0.10"
ReachabilityAnalysis = "0.14"

[extras]
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["DifferentialEquations", "Plots", "Test"]
